# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

### Send POST request with json body
POST http://127.0.0.1:8000/sms
Content-Type: application/json

{
  "sms": {
    "sender": "ja",
    "message": "content"
  },
  "auth": "oof"
}

### Send POST request with json body
POST http://127.0.0.1:8000/sms
Content-Type: application/json

{
}
